spring.application.name=dg-heritage
spring.datasource.url=jdbc:postgresql://localhost:5432/dg_preprod
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

cloudinary.cloud_name=dpdtkg2yd
cloudinary.api_key=963842314714882
cloudinary.api_secret=ebORIOdSQyyaWUYAYW88zKYttfI